name: Sending repo data to backend

on:
  push: 
    branches:
      - "main"

jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository Metadata
        uses: varunsridharan/action-repository-meta@2.2
        with:
          url: "https://8000-trilogygrou-processbppl-csl0gsl8fqk.ws.trilogy.devspaces.com/analytics/dummy/"
          method: "POST"
